import { AppShell } from "@/components/app-shell";
import { CollectionPage } from "@/components/collection-page";
import { prisma } from "@/lib/prisma";
import { requireWorkspaceContext } from "@/lib/workspace";
import { EmailComposer } from "@/components/email-composer";
import { OutboundEmailList } from "@/components/outbound-email-list";

export const metadata = { title: "Inbox" };
export default async function InboxPage() {
  const context = await requireWorkspaceContext();
  const [emails, contacts, groups, mailbox, outbound] = await Promise.all([prisma.email.findMany({ where: { organizationId: context.organization.id }, orderBy: { receivedAt: "desc" }, take: 100 }), prisma.contact.findMany({ where: { organizationId: context.organization.id }, select: { id: true, name: true, email: true }, orderBy: { name: "asc" } }), prisma.contactGroup.findMany({ where: { organizationId: context.organization.id }, select: { id: true, name: true, _count: { select: { members: true } } }, orderBy: { name: "asc" } }), prisma.mailboxConnection.findFirst({ where: { organizationId: context.organization.id, userId: context.user.id, provider: "GMAIL", status: "ACTIVE" }, select: { id: true } }), prisma.outboundEmail.findMany({ where: { organizationId: context.organization.id, createdById: context.user.id }, orderBy: { createdAt: "desc" }, take: 20, select: { id: true, toName: true, toEmail: true, subject: true, status: true, scheduledAt: true, sentAt: true, lastError: true } })]);
  return <AppShell workspaceName={context.organization.name} userName={context.user.name}><EmailComposer contacts={contacts} groups={groups.map((group) => ({ id: group.id, name: group.name, memberCount: group._count.members }))} mailboxConnected={Boolean(mailbox)} /><OutboundEmailList mailboxConnected={Boolean(mailbox)} messages={outbound.map((message) => ({ ...message, scheduledAt: message.scheduledAt?.toISOString() || null, sentAt: message.sentAt?.toISOString() || null }))} /><CollectionPage eyebrow="Communication" title="Inbox" subtitle={mailbox ? "Synced Gmail and imported communication available to your assistant." : "Connect Gmail in Settings, or import an important message manually."} action="Import email" resource="inbox" emptyTitle="No email imported" emptyBody="Connect Gmail in Settings or paste an important message to make it searchable and available to the Command Center." fields={[
    { name: "subject", label: "Subject", type: "text", required: true }, { name: "sender", label: "Sender", type: "text", required: true, placeholder: "name@company.com" }, { name: "receivedAt", label: "Received", type: "datetime-local", required: true }, { name: "bodyText", label: "Message", type: "textarea", required: true }, { name: "isImportant", label: "Mark as important", type: "checkbox" },
  ]} initialRecords={emails.map((email) => ({ id: email.id, title: email.subject, subtitle: email.bodyText?.slice(0, 180), href: `/inbox/${email.id}`, badge: email.isImportant ? "Important" : "Email", meta: [email.sender, new Intl.DateTimeFormat("en", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(email.receivedAt)] }))} /></AppShell>;
}
