"use client";

import { FileText, LoaderCircle, Search, Upload } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { LocalDateTime } from "@/components/local-date-time";
import { useRouter } from "next/navigation";

type DocumentItem = { id: string; name: string; mimeType: string; sizeBytes: number; status: string; excerpt: string | null; createdAt: string };
export function DocumentLibrary({ initialDocuments }: { initialDocuments: DocumentItem[] }) {
  const router = useRouter(); const [documents, setDocuments] = useState(initialDocuments); const [query, setQuery] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState<string | null>(null);
  const visible = useMemo(() => documents.filter((document) => `${document.name} ${document.excerpt || ""}`.toLowerCase().includes(query.toLowerCase())), [documents, query]);
  async function upload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setPending(true); setError(null); try { const response = await fetch("/api/documents", { method: "POST", body: data }); const payload = await response.json(); if (!response.ok) setError(payload.error || "Upload failed"); else { setDocuments((current) => [{ ...payload.document, excerpt: payload.document.extractedText?.slice(0, 220) || null }, ...current]); form.reset(); router.refresh(); } } catch { setError("Unable to reach Elara. Check your connection and try again."); } finally { setPending(false); } }
  return <><div className="page-heading compact-heading"><div><p className="eyebrow">Knowledge</p><h1>Documents</h1><p className="page-subtitle">Upload, search, and ground Elara in the files that matter.</p></div><form className="upload-button" onSubmit={upload}><label className="primary-button">{pending ? <LoaderCircle className="spin" size={16} /> : <Upload size={16} />}Upload document<input aria-label="Upload document" name="file" type="file" required disabled={pending} accept=".pdf,.docx,.xlsx,.pptx,.png,.jpg,.jpeg,.webp,.txt,.md,.csv,.rtf" onChange={(event) => event.currentTarget.form?.requestSubmit()} /></label></form></div>{error && <p className="form-error" role="alert">{error}</p>}<div className="document-search"><Search size={15} /><input aria-label="Search documents" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search document names and extracted text" /></div><section className="panel document-panel">{visible.length ? <div className="record-grid">{visible.map((document) => <article className="record-card document-card" key={document.id}><div className="document-icon"><FileText size={19} /></div><span className="record-badge">{document.status}</span><h2><a href={`/api/documents/${document.id}`} target="_blank" rel="noopener noreferrer">{document.name}</a></h2><p>{document.excerpt || (document.status === "READY" ? "Stored securely. No text was extracted from this file type." : "Text extraction was not completed.")}</p><div className="record-meta"><span>{formatBytes(document.sizeBytes)}</span><span><LocalDateTime value={document.createdAt} dateOnly /></span></div></article>)}</div> : <div className="task-empty"><div className="empty-icon"><FileText size={20} /></div><h2>No matching documents</h2><p>Upload a supported office file, PDF, image, or text file. Extracted content becomes available to workspace search and grounded AI.</p></div>}</section></>;
}
function formatBytes(value: number) { return value < 1024 * 1024 ? `${Math.max(1, Math.round(value / 1024))} KB` : `${(value / 1024 / 1024).toFixed(1)} MB`; }
